app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('login', ['as' =>'login', 'uses' => 'DashboardController@getLogin']);
Route::post('auth/login', ['as' =>'auth/login', 'uses' => 'DashboardController@postLogin']);
Route::get('auth/logout', ['as' => 'auth/logout', 'uses' => 'DashboardController@getLogout']);

Route::get('registro', ['as' =>'registro.create', 'uses' => 'DashboardController@getRegistro']);
Route::post('registro', ['as' =>'registro.store', 'uses' => 'DashboardController@postRegistro']);

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::group(['middleware' => 'auth'], function () {

  Route::get('dashboard', [
      'as' => 'dashboard', 'uses' => 'DashboardController@index'
  ]);

  Route::get('dashboard/mis-paquete', [
      'as' => 'paquete', 'uses' => 'PaqueteController@index'
  ]);

  Route::get('dashboard/cliente-paquete', [
      'as' => 'clientes', 'uses' => 'PaqueteController@index'
  ]);

  Route::get('dashboard/paquete/registrar', [
      'as' => 'paquete.registrar', 'uses' => 'PaqueteController@registrar'
  ]);

  Route::post('dashboard/paquete/guardar', [
      'as' => 'paquete.guardar', 'uses' => 'PaqueteController@guardar'
  ]);

  Route::get('dashboard/paquete/detalle/{paquete}', [
      'as' => 'paquete.detalle', 'uses' => 'PaqueteController@detalle'
  ]);

  Route::get('dashboard/paquete/movimiento/{paquete}', [
      'as' => 'paquete.movimiento', 'uses' => 'PaqueteController@movimiento'
  ]);

  Route::post('dashboard/movimiento/guardar/', [
      'as' => 'paquete.guardarMovimiento', 'uses' => 'PaqueteController@guardarMovimiento'
  ]);

  Route::get('dashboard/tarifa', [
      'as' => 'tarifa', 'uses' => 'TarifaController@index'
  ]);

  Route::get('dashboard/tarifa/editar', [
      'as' => 'tarifa.editar', 'uses' => 'TarifaController@editar'
  ]);

  Route::post('dashboard/tarifa/actualizar/', [
      'as' => 'tarifa.actualizar', 'uses' => 'TarifaController@actualizar'
  ]);

  Route::get('dashboard/preguntas', [
      'as' => 'preguntas', 'uses' => 'PreguntaController@index'
  ]);

  Route::get('dashboard/pregunta/registrar', [
      'as' => 'pregunta.registrar', 'uses' => 'PreguntaController@registrar'
  ]);

  Route::post('dashboard/pregunta/guardar', [
      'as' => 'pregunta.guardar', 'uses' => 'PreguntaController@guardar'
  ]);

  Route::get('dashboard/pregunta/detalle/{id}', [
      'as' => 'pregunta.detalle', 'uses' => 'PreguntaController@detalle'
  ]);

  Route::post('dashboard/pregunta/contestar', [
      'as' => 'pregunta.comentario', 'uses' => 'PreguntaController@comentario'
  ]);

  Route::get('dashboard/calcular-costo', [
      'as' => 'costo', 'uses' => 'PaqueteController@calcularCosto'
  ]);

  Route::post('dashboard/resultado-costo', [
      'as' => 'costo.resultado', 'uses' => 'PaqueteController@resultadoCosto'
  ]);

});

/*Route::get('dashboard/tarifa', function () {
    return view('tarifa.index');
});

Route::get('dashboard/conversacion', function () {
    return view('conversacion.index');
});*/

app/Pregunta.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Jenssegers\Date\Date;

class Pregunta extends Model
{
    use SoftDeletes;

    public function autor()
    {
        return $this->belongsTo('App\Usuario','usuario_id','id');
    }

    public function comentarios()
    {
         return $this->hasMany('App\Comentario');
    }

    public function getCreatedAtAttribute($value){
      return new Date($value);
      //return new Date($value, new DateTimeZone('Americas/Caracas'));
    }

    public function getAutorTipoAttribute(){
      if($this->autor()->tipo=='cliente'){
         return 'Comentario del (Cliente):'.' '.$this->autor()->nombre.', '.$this->autor()->apellido;
      }else{
         return 'Comentario del (Administrador):'.' '.$this->autor()->nombre.', '.$this->autor()->apellido;
      }
    }
}

resources/views/conversacion/crear.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="well p-b-50">
  <form method="POST" action="{{route('pregunta.guardar')}}">
        {{ csrf_field() }}
        <div class="col-md-12">
        <div class="form-group p-t-0">
            <label class="f-15">Preguta</label>
            <input type="text" class="form-control" name="pregunta" placeholder="Pregunta" value="{{ old('pregunta') }}">
            <span class="text-danger" >{{$errors->first('pregunta')}}</span>
        </div>
       </div>
       <div class="col-md-12">
        <div class="form-group p-t-0">
            <label class="f-15">Descripción</label>
            <textarea type="text" class="form-control" name="descripcion" placeholder="Descripcion">{{ old('descripcion') }}</textarea>
            <span class="text-danger" >{{$errors->first('descripcion')}}</span>
        </div>
      </div>
      <div class="clearfix"></div>
      <hr>
      <div class="text-right">
        <button type="submit" class="btn btn-primary">Guardar</button>
      </div>
  </form>
</div>
@endsection

resources/views/conversacion/detalle.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading f-20"><b>Pregunta: {{$pregunta->titulo}}</b></div>
  <div class="panel-body">
    <p class="f-18">{{$pregunta->descripcion}}</p>
    <br>
    <div class="col-md-12 text-right"><b>Fecha publicacion: </b>{{$pregunta->created_at->format('j')}} de {{$pregunta->created_at->format('F Y h:i A')}}</div>
    <div class="col-md-12 text-right"><b>Autor: </b>{{$pregunta->autor->nombre}}, {{$pregunta->autor->apellido}}</div>
    <br><br>
    <hr>
    <p class="f-18 text-right"><b># Comentarios: ({{count($pregunta->comentarios)}})</b></p>
  </div>

  <!-- List group -->
  <div class="list-group">
    @foreach($pregunta->comentarios as $comentario)
    <a href="#" class="list-group-item">
      <h4 class="list-group-item-heading text-right f-15"><b>Autor:</b> {{$comentario->autor_tipo}}
        | <b>Fecha:</b> {{$comentario->created_at->format('d-m-Y h:i A')}}</h4>
        <br>
      <p class="list-group-item-text f-18"><b>Comentario:</b></p>
      <p class="p-l-30 p-r-30 text-justify f-18"> {{$comentario->mensaje}}</p>
      <br>
    </a>
    @endforeach
  </div>
</div>
<div class="well p-b-50">
  <form method="POST" action="{{route('pregunta.comentario')}}">
      {{ csrf_field() }}
      <div class="col-md-12">
        <div class="form-group p-t-0">
            <label class="f-15">Comentario</label>
            <textarea type="text" maxlength="250" class="form-control" name="comentario" placeholder="Comentario">{{ old('comentario') }}</textarea>
            <span class="text-danger" >{{$errors->first('comentario')}}</span>
        </div>
      </div>
      <div class="clearfix"></div>
      <hr>
      <div class="text-right">
        <input type="hidden" name="id" value="{{$pregunta->id}}">
        <button type="submit" class="btn btn-primary">Guardar</button>
      </div>
  </form>
</div>
@endsection

resources/views/conversacion/index.blade.php
@extends('layouts.dashboard')
@section('content')

@if (session('mensaje_ok'))
     <div class="alert alert-success text-center">
         {{ session('mensaje_ok') }}
     </div>
@endif

@if (Auth::user()->tipo=='cliente')
<a class="btn btn-primary" href="{{route('pregunta.registrar')}}">Registrar Pregunta</a>
<hr>
@endif

<table class="table text-center table-bordered">
  <thead>
    <tr>
      <th class="text-center" >Titulo de la pregunta</th>
      <th class="text-center" >Estatu</th>
      <th class="text-center" >Acciones</th>
    </tr>
  </thead>
  <tbody>
  @foreach($preguntas as $pregunta)
    <tr>
      <td>{{$pregunta->titulo}}</td>
      <td>{{$pregunta->estatus}}</td>
      <td>
        <!-- Small button group -->
        <div class="btn-group">
          <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Opciones <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li><a href="{{route('pregunta.detalle',['pregunta'=>$pregunta->id])}}">Detalle</a></li>
          </ul>
        </div>
      </td>
    <tr>
  @endforeach
  </tbody>
</table>

@endsection